### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by nevesing** [basicrum/backoffice#134] opened 2020-06-17 23:07 UTC
I just came across this project and wanted to try. So I installed docker and docker-compose. When i ran "make init" it went through multiple steps and failed with below error during composer installation. Not sure if it is firewall issue or something else.

`OK: 14 MiB in 35 packages
Removing intermediate container f5824f2584b9
 ---> a9de0e24ede2
Step 4/6 : ARG XDEBUG_ON="N"
 ---> Running in ac9d2ca863bd
Removing intermediate container ac9d2ca863bd
 ---> 302aec7a8e48
Step 5/6 : RUN if [ "${XDEBUG_ON}" == "Y" ]; then     apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS     && pecl install xdebug     && docker-php-ext-enable xdebug     && apk del --purge .phpize-deps;  fi
 ---> Running in f631aed6b2d0
Removing intermediate container f631aed6b2d0
 ---> 33f0144f2fb3
Step 6/6 : RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"     && php composer-setup.php --filename=composer --install-dir=/usr/local/bin     && php -r "unlink('composer-setup.php');"
 ---> Running in 98a4f157e0f9

Warning: copy(): SSL: Connection reset by peer in Command line code on line 1

Warning: copy(): Failed to enable crypto in Command line code on line 1

Warning: copy(https://getcomposer.org/installer): failed to open stream: operation failed in Command line code on line 1
Could not open input file: composer-setup.php
ERROR: Service 'symfony_app' failed to build: The command '/bin/sh -c php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"     && php composer-setup.php --filename=composer --install-dir=/usr/local/bin     && php -r "unlink('composer-setup.php');"' returned a non-zero code: 1
make: *** [up] Error 1
`

**Comment by ceckoslab** [comment] 2020-06-18 09:30
Hello @nevesing 

We can't reproduce the issue that you are experiencing but we did some research and we found 2 potential reasons:
 * There are some issues when you are on IPv6
 * You may have some problems with ca-certificates

Could you try this workaround?

In docker/symfony_app/Dockerfile change **https://getcomposer.org/installer** to **http://getcomposer.org/installer**

On a side note: 
What would you like to get from Basic RUM? We are still at very early and unstable stage but we would like to get a feedback from people who will use the system.


cc @eliskovets 

Evgeny, what do you think if we use this technique in order to avoid such problems in the future?
```
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
```

**Comment by eliskovets** [comment] 2020-06-18 09:59
Hi @ceckoslab ,
I would say it's a preferable way to install it. I've been using this for some projects in the past and we can definitely give it a try :)

**Comment by nevesing** [comment] 2020-06-18 13:06
Thanks for the quick response. My current requirement is to host a server which collects the beacon data and I can use our existing backends like splunk, graphite or datadog. I have tried Boomcatch and it is not working as expected. Also it is not up to date.

BasicRUM - Since it is an active project I thought of giving it a try. It is better to mention the prerequisites in the document like docker, docker-compose and so-on. Also it will be nice to host a simple backend server for use cases like I mentioned above.


I changed the Dockerfile and now I am getting HTTP 503 error. How do I try your 2nd suggestion?


_____________________

Step 6/6 : RUN php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"     && php composer-setup.php --filename=composer --install-dir=/usr/local/bin     && php -r "unlink('composer-setup.php');"
 ---> Running in 552dd5b2fae5

Warning: copy(http://getcomposer.org/installer): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable
 in Command line code on line 1
Could not open input file: composer-setup.php
ERROR: Service 'symfony_app' failed to build: The command '/bin/sh -c php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"     && php composer-setup.php --filename=composer --install-dir=/usr/local/bin     && php -r "unlink('composer-setup.php');"' returned a non-zero code: 1
make: *** [up] Error 1
[

**Comment by ceckoslab** [comment] 2020-06-18 20:13
Hello @nevesing 

We just merged a fix to master. Could you update your local copy and run **make init**?

Regarding:
> Thanks for the quick response. My current requirement is to host a server which collects the beacon data and I can use our existing backends like splunk, graphite or datadog. I have tried Boomcatch and it is not working as expected. Also it is not up to date.

It really depends what you want to do with the beacons. We have separate small project https://github.com/basicrum/boomerang-beacon-catcher which is far from perfect but it can persist raw beacons for you. (I still have to push some local changes with fixes).

Basic RUM is active but far from even calling it alpha version. We are still working on defining a proper DB schema and separating the main logical parts in components. If you want to just persist beacons just let me know and I will polish and push changes for https://github.com/basicrum/boomerang-beacon-catcher . If you want to use more from Basic RUM, e.g. to read decoded beacon data from a MySql DB and import it in other systems you will have to wait couple of weeks before we stabilize the situation.

Do you already have an idea what kind of metrics you want to display? Also take a look here if you want to understand about the DB schema: https://github.com/basicrum/backoffice/wiki/Architecture-diagrams#Monolith-Concept

> BasicRUM - Since it is an active project I thought of giving it a try. It is better to mention the prerequisites in the document like docker, docker-compose and so-on. Also it will be nice to host a simple backend server for use cases like I mentioned above.

Thanks we will add this soon! I think that we wiped out part of our README couple of week ago :)

**Comment by nevesing** [comment] 2020-06-18 20:38
I appreciate all your effort.

I cloned the latest repo and 'make init' worked just fine. I logged into the portal (8086) and I see this message " Development version! Contains test data for period (June 18, 2020 - June 18, 2020)." but there is no data. Not sure if it is expected.

I think I can make use of 'boomerang-beacon-catcher' once you update it. And then I will read the JSON data from filesystem as mentioned in the docs. I am mostly looking for metrics produced by the APIs like Navigation Timing, Roundtrip Timing and Resource Timing using the Boomerang JS library.

**Comment by ceckoslab** [comment] 2020-06-18 21:12
Thanks @nevesing 

Could you run **make demo** ?

I updates slightly the README by adding prerequisites.

I will keep this ticket open and will close it after I push changes for the Beacon catcher.

**Comment by nevesing** [comment] 2020-06-18 21:27
**Make demo results:**

curl https://s3.eu-central-1.amazonaws.com/com.basicrum.demo/test_data/may-july-2019.sql.gz -o may-july-2019.sql.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  129M  100  129M    0     0  24.4M      0  0:00:05  0:00:05 --:--:-- 26.3M
gunzip -c may-july-2019.sql.gz | docker-compose -f docker/docker-compose.yml exec -T db sh -c 'mysql ${MYSQL_DATABASE}'
ERROR 1062 (23000) at line 755: Duplicate entry '1' for key 'PRIMARY'
read unix @->/var/run/docker.sock: read: connection reset by peer
make: *** [demo] Error 1

So how do I send my current beacon data to basicrum? I am not sure if it is covered in the docs.

**Comment by ceckoslab** [comment] 2020-06-18 21:57
Hello @nevesing 

Seems that you already have some data in the DB ...

Could you try:
```
make rebuild
make demo
```

In order to persist beacons:

Set this beacon URL for Boomerang JS: http://127.0.0.1:8086/beacon/catcher.php
The beacons will in projectroot/var/beacons/raw/

We filed a ticket in order to document this: https://github.com/basicrum/backoffice/issues/137

**Comment by nevesing** [comment] 2020-06-18 22:22
Yes it worked this time and I am able to see the dashboard. Thank you. (I saw /var/www/html/* already exists message multiple times during 'make demo').

**Comment by nevesing** [comment] 2020-06-18 22:48
I am able to send my beacon to catcher.php.

**Questions:**

1) Is there a way to change the port (8086)
2) Beacon log is stored inside the container 'docker_symfony_app' and how do I volume mount to local

I wish you could consider these changes in boomerang-beacon-catcher project

**Comment by ceckoslab** [comment] 2020-06-19 09:01
Hello @nevesing 

Answers:

1. You can change the docker-compose file here: https://github.com/basicrum/backoffice/blob/master/docker/docker-compose.yml#L62
2. The beacons must be visible on your host operating system: **{{project root where you did git clone}}/var/beacons/raw/**

Then could cleaned from time to time because we have a special cron job that bundles the raw beacons periodically ... I can't check this right now.

Expect some updates on **boomerang-beacon-catcher** next week.

**Comment by nevesing** [comment] 2020-06-19 14:03
Thanks I found it.

**Comment by ceckoslab** [comment] 2020-06-30 16:14
Hello @nevesing 

You may check now the beacon catcher repo. I did some adjustments and now the beacon catcher exposes the beacons folder to the host os:  https://github.com/basicrum/boomerang-beacon-catcher

**Closed by ceckoslab** 2020-06-30 16:14 UTC

**Comment by nevesing** [comment] 2020-06-30 17:48
Thank you. I will check it out.
